#!/usr/bin/env python3
"""Reproducibility manifest: SHA-256 of critical artifacts + env + data identity.

Phase 1.5 / item 1b. Hashing all 181k eval FLACs is impractical, so this records
the *identity* of the eval set (count, bytes, source) plus exact SHA-256 of the
small artifacts a result actually depends on (checkpoint, config, CM keys, cached
scores) and the resolved versions of the key libraries.

Usage:
    python3 scripts/make_manifest.py > docs/REPRODUCIBILITY_MANIFEST.md
"""

from __future__ import annotations

import hashlib
import importlib.metadata as md
import os
import sys
from datetime import date

CKPT_ROOT = os.environ.get("VG_CKPT_ROOT", "/srv/thabet/voiceguard-checkpoints")

# Small, result-defining artifacts to hash exactly.
ARTIFACTS = [
    f"{CKPT_ROOT}/runs/xlsr_aasist_v9c/model_best.pt",
    f"{CKPT_ROOT}/runs/xlsr_aasist_v9c/config.json",
    f"{CKPT_ROOT}/asvspoof2021_LA_official/keys/LA/CM/trial_metadata.txt",
    f"{CKPT_ROOT}/runs/scores_v9c_official.npz",
]

# Dataset whose per-file hashing is impractical — record identity instead.
DATASETS = {
    "ASVspoof 2021 LA eval (official)": (
        f"{CKPT_ROOT}/asvspoof2021_LA_official/ASVspoof2021_LA_eval/flac",
        "Zenodo 4837263 + asvspoof.org CM keys",
    ),
}

PKGS = ["torch", "torchaudio", "transformers", "numpy", "scipy", "scikit-learn",
        "soundfile", "librosa", "onnxruntime", "pyarrow"]


def sha256(path: str, buf: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(buf):
            h.update(chunk)
    return h.hexdigest()


def dir_identity(path: str) -> tuple[int, int]:
    n = total = 0
    for root, _, files in os.walk(path):
        for fn in files:
            n += 1
            total += os.path.getsize(os.path.join(root, fn))
    return n, total


def main() -> None:
    print("# Reproducibility Manifest\n")
    print(f"_Generated by `scripts/make_manifest.py` on {date.today()}. "
          f"Re-run to refresh. Verify a file with `sha256sum <path>`._\n")

    print(f"**Python** {sys.version.split()[0]}\n")
    print("## Environment (key libraries)\n")
    print("| package | version |\n|---------|---------|")
    for p in PKGS:
        try:
            print(f"| {p} | `{md.version(p)}` |")
        except md.PackageNotFoundError:
            print(f"| {p} | _not installed_ |")

    print("\n## Artifact SHA-256\n")
    print("| artifact | size (MB) | sha256 |\n|----------|----------:|--------|")
    for a in ARTIFACTS:
        if os.path.exists(a):
            mb = os.path.getsize(a) / 1e6
            print(f"| `{os.path.basename(a)}` | {mb:.2f} | `{sha256(a)}` |")
        else:
            print(f"| `{os.path.basename(a)}` | — | _missing_ |")

    print("\n## Dataset identity (per-file hashing impractical)\n")
    print("| dataset | files | bytes | source |\n|---------|------:|------:|--------|")
    for name, (path, src) in DATASETS.items():
        if os.path.isdir(path):
            n, total = dir_identity(path)
            print(f"| {name} | {n:,} | {total:,} | {src} |")
        else:
            print(f"| {name} | — | — | {src} (not on this host) |")


if __name__ == "__main__":
    main()
